library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
# library(plotly)
# library(readr)
# library(lubridate)
# library(reshape2)
library(readxl)
# library(xtable)
library(shinyWidgets)
library(colourpicker)
# library(reshape2)
# library(hrbrthemes)
# library(viridis)
# library(ggthemes)

# install.packages("shiny")
# install.packages("dplyr")
# install.packages("tidyr")
# install.packages("ggplot2")
# install.packages("plotly")
# install.packages("readr")
# install.packages("lubridate")
# install.packages("reshape2")
# install.packages("readxl")
# install.packages("xtable")
# install.packages("shinyWidgets")
# install.packages("colourpicker")
# install.packages("hrbrthemes")
# install.packages("viridis")
# install.packages("ggthemes")

